### ISSUE TITLE
DefaultColorSchemes data section seems to be wrong

### ISSUE THREAD

**Issue by SicroAtGit** [fantaisie-software/purebasic#101]
https://github.com/fantaisie-software/purebasic/blob/9cc037408cac54fe73e9b6c9bde723d01af2adb2/PureBasicIDE/Preferences.pb#L5465-L5474

The comment does not seem to be correct anymore. After the color scheme name there are 3 instead of 2 long values before the syntax colors start.

1. Color scheme name
2. Front color of the tool panel
3. Background color of the tool panel
4. ?
5. First syntax color

**Comment by kenmo-pb** [comment]
Luckily the problem is just that the comments are outdated / misaligned.

If you compare against the `#COLOR` Enumeration in `Common.pb`, and also `LoadPreferences()` in `Preferences.pb`, you'll see that the order really is:

- SchemeName$
- ToolsPanelFrontColor
- ToolsPanelBackColor
- #COLOR_ASMKeyword
- #COLOR_GlobalBackground :warning: 
- #COLOR_BasicKeyword
- ...

`#COLOR_GlobalBackground` is missing from the comments, and `#COLOR_ASMKeyword` starts one line too late. (You can also confirm this by looking at what colors the hex values represent.)

So it should look like this below. Do you want to submit a correction PR? Or else I can.

![image](https://user-images.githubusercontent.com/25482520/95015236-e2907880-0619-11eb-9bf7-e075f01c60ec.png)

**Comment by SicroAtGit** [comment]
Didn't have much time that day and just to be on the safe side I reported it as an issue.

Thank you for the investigation and for fixing it.
