### ISSUE TITLE
purebasic IDE “Format indentation” bug

### ISSUE THREAD

**Issue by diskay** [fantaisie-software/purebasic#111]
https://www.purebasic.fr/english/viewtopic.php?f=42&t=74612

An attempt to use "Format indentation" on the following code produced strange results:
Code:
a(0, 1, "你好世界！", 100)
Debug 1

It looks like this

Code:
a(0, 1, "你好世界！", 100)
(some space)Debug 1

I've found the problem

It is located in:

https://github.com/fantaisie-software/purebasic/blob/6635e3951f08a088a3d3f3bb0cac0ae29bc778e3/PureBasicIDE/SourceParser.pb#L421

PureBasicIDE/ SourceParser.pb

line 421-430,433

Delete these lines and it's OK :D

**Comment by tajmone** [comment]
@diskay, some time has passed since you've opened this Issue, but no PR has followed.

I'm not sure I understand, you mentioned having spotted both the problem and the solution, so it would reasonable to expect that you create a pull request to fix the bug, Since the problem you describe manifests with the Chinese language (I'm guessing it's Chinese, but I could be wrong), it requires a Chinese native speaker to implement the fix and test that it works as expected.

**Comment by fantaisie-software** [comment]
Should be opened in the english bug section of the forum. I can't reproduce it here BTW and the fix looks wrong as the IDE is now unicode.
