### ISSUE TITLE
HTML-BUILD.bat : Don't work on a non-default installation

### ISSUE THREAD

**Issue by Naheulf** [fantaisie-software/purebasic#147]
As tell is the title the [/Documentation/HTML-BUILD.bat](https://github.com/fantaisie-software/purebasic/blob/devel/Documentation/HTML-BUILD.bat) script don't works with a non-default installation.

For now I see two points that don't works:
 - it only check for `SDK\DocMaker\DocMaker.exe` in the default installation path
 - the conditional pause at the end or the file is never executed (at least on my  computer)

I found fix for theses two issues. I will create a PR soon.

**Comment by tajmone** [comment]
> As tell is the title the /Documentation/HTML-BUILD.bat script don't works with a non-default installation.

no, it relies on PureBasic being installed in the default Windows' installation path (`%ProgramFiles%`):

```batch
:: Check that DocMaker is available:
SET DocMaker="%ProgramFiles%\PureBasic\SDK\DocMaker\DocMaker.exe"
IF NOT EXIST %DocMaker% GOTO :DocMakerNotFound
```

what we could do here is add an extra check, e.g. if `%DocMaker%` is already defined (by the user) when the script is launched, then use the variable as it is, instead of defining it. In this case, the script will have to take the variable for good, at face value, because `DocMaker.exe` can't be testing via the command line (e.g. `DocMaker.exe -v`) since there are command line switches to query for version info, help, etc.

Alternatively, we could check for a variable pointing to a custom PureBasic installation path, like `PUREBASIC_HOME` (which is already used by the build scripts) and then probe for the existence of `\SDK\DocMaker\DocMaker.exe` relatively to it. This approach has the advantage that it integrates better with other env vars that might have been added for other scripts in the repository (e.g. the main build scripts and Makefiles) and can reduce the number of env vars end users need to define (especially if adding them permanently to their User/System settings) — `PUREBASIC_HOME` is what these scripts are already using.


> the conditional pause at the end or the file is never executed (at least on my computer)

When creating an Issue, you should _always_ mention which OS are you working under! (if I remember correctly, from other Issues, you're using Win 7)

The script is only supposed to pause if launched from File Explorer:

```batch
:EndScript
:: Only pause before quitting if the script was launched via File Explorer:
ECHO "%cmdcmdline%" | FINDSTR /IC:"%~dp0" >nul && PAUSE
```

There doesn't seem to be anything special there that would justify incompatibility between Win 10 and other Windows versions (but you never know, the CMD is known to have inconsistent behavior across Windows editions).

What do you get on your machine if you type `ECHO "%cmdcmdline%"` in the command prompt?

**Comment by Naheulf** [comment]
# Custom PB Installation Path

> no, it relies on PureBasic being installed in the default Windows' installation path (`%ProgramFiles%`):
> 
> ```batchfile
> :: Check that DocMaker is available:
> SET DocMaker="%ProgramFiles%\PureBasic\SDK\DocMaker\DocMaker.exe"
> IF NOT EXIST %DocMaker% GOTO :DocMakerNotFound
> ```

`%ProgramFiles%\PureBasic` is the default installation path. If chose to install PB in `%ProgramFiles%\PureBasic\PB_5.73` it will not works because it's not a default installation.


> what we could do here is add an extra check, e.g. if `%DocMaker%` is already defined (by the user) when the script is launched, then use the variable as it is, instead of defining it.

Added to my draft

> In this case, the script will have to take the variable for good, at face value, because `DocMaker.exe` can't be tested via the command line (e.g. `DocMaker.exe -v`) since there are no command line switches to query for version info, help, etc.

I can still test if the file exist. Simple test but mandatory to use this var later

> Alternatively, we could check for a variable pointing to a custom PureBasic installation path, like `%PUREBASIC_HOME%` (which is already used by the build scripts) and then probe for the existence of `\SDK\DocMaker\DocMaker.exe` relatively to it. This approach has the advantage that it integrates better with other env vars that might have been added for other scripts in the repository (e.g. the main build scripts and Makefiles) and can reduce the number of env vars end users need to define (especially if adding them permanently to their User/System settings) — `%PUREBASIC_HOME%` is what these scripts are already using.

Already done among some others ways to find it (see PR). However I don't know in what order to put them.

# Script Pause

> When creating an Issue, you should _always_ mention which OS are you working under! (if I remember correctly, from other Issues, you're using Win 7)

Oooops. I forgot It. I'm on windows 8.1 x64.

> The script is only supposed to pause if launched from File Explorer:

That why I said "the conditional pause at the end or the file is never executed"... even if I launch the bat from explorer.exe.

## Additional Test

> You could try and edit the above lines as follows:
> 
> ```batchfile
> :EndScript
> :: Only pause before quitting if the script was launched via File Explorer:
> ECHO %%cmdcmdline%%: "%cmdcmdline%"
> ECHO %%~dp0: "%~dp0"
> ECHO "%cmdcmdline%" | FINDSTR /IC:"%~dp0" >nul && PAUSE
> ```
> 
> where the next-to-last added lines will allow you to see the value of `%cmdcmdline%` and `%~dp0` when invoking the script from File Explorer and from the CMD — just in case your Win version is handling them differently (I doubt it, but you never know).

If I also add an unconditional `PAUSE` just before the `EXIT /B` I get this running the script from explorer.exe :
```

##############################################################################
#                                                                            #
#                    PureBasic Help HTML Preview Builder                     #
#                                                                            #
##############################################################################
Missing parameter

  de   -- Builds German documentation in:  "German\HTML\"
  en   -- Builds English documentation in: "English\HTML\"
  fr   -- Builds French documentation in:  "French\HTML\"
  all  -- Builds all three locales.
%cmdcmdline%: "C:\Windows\system32\cmd.exe /c ""D:\Users\Perso\Scripts\purebasic\fantaisie-software\purebasic\Documentation\HTML-BUILD.bat" ""
%~dp0: "D:\Users\Perso\Scripts\purebasic\fantaisie-software\purebasic\Documentation\"
Appuyez sur une touche pour continuer...
```
and this running the script from cmd.exe:
```

D:\Users\Perso\Scripts\purebasic\fantaisie-software\purebasic\Documentation>HTML-BUILD.bat

##############################################################################
#                                                                            #
#                    PureBasic Help HTML Preview Builder                     #
#                                                                            #
##############################################################################
Missing parameter

  de   -- Builds German documentation in:  "German\HTML\"
  en   -- Builds English documentation in: "English\HTML\"
  fr   -- Builds French documentation in:  "French\HTML\"
  all  -- Builds all three locales.
%cmdcmdline%: ""C:\Windows\System32\cmd.exe" "
%~dp0: "D:\Users\Perso\Scripts\purebasic\fantaisie-software\purebasic\Documentation\"
Appuyez sur une touche pour continuer...

D:\Users\Perso\Scripts\purebasic\fantaisie-software\purebasic\Documentation>
```

**Comment by tajmone** [comment]
> If chose to install PB in %ProgramFiles%\PureBasic\PB_5.73 it will not works because it's not a default installation.

That's what I meant by "no" (i.e. "no, it won't work"). I can't think of any viable way to use non-default install paths except by defining a custom variable (attempting to locate `DocMaker.exe` is not a good alternative IMO).

> I get this running the script from explorer.exe :

The result seems correct, I can't understand why the pause is not working. The line:

```batch
ECHO "%cmdcmdline%" | FINDSTR /IC:"%~dp0" >nul && PAUSE
```

... detects if it was launched from File Explorer by checking if the `%~dp0` is a subset of the `%cmdcmdline%` string — which your pasted results show it is. So I have no idea why it's not working as expected.

**Comment by tajmone** [comment]
OK, I worked out the problem, it's due to the surrounding quotes. Should have been changed to:

```batch
ECHO %cmdcmdline% | FINDSTR /ILC:%~dp0 >nul && PAUSE
```

I'm not entirely show if that's going to work as expected with paths that contains spaces, though!

but your proposed fix in #148 might be even better:

```batch
ECHO "%cmdcmdline%" | FINDSTR /IC:"%~0" >nul && PAUSE
```

because by removing the `dp` from the parameter expansion you shuould end up with two identical strings (regardless of the enclosing quotes).

**Comment by Naheulf** [comment]
> I'm not entirely show if that's going to work as expected with paths that contains spaces, though!

I just tested it: if fail. FINDSTR display an error in the console:
```
FINDSTR : Impossible d'ouvrir umentation\
```

(I rename the `documentation` folder to `doc umentation`)

 On few forum people also look for `%ComSpec%`. However I can't say if it's better or not than my fix.

**Comment by tajmone** [comment]
Maybe the alternative solution could be to wait for the user to press a key before exiting the script, so we're sure everyone has a chance to read the output. The downside would be that it won't interact well with automated toolchains, but then ... this batch script was just meant as a simple solution for quickly testing the HMTL Help docs while editing, and not as a general purpose solution.

**Comment by Naheulf** [comment]
We can keep the conditional pause for now and replace it with a plain `PAUSE` in the future if it still don't works for someone. (Or test variants with ComSpec) ¯\\\_(ツ)\_/¯
