### ISSUE TITLE
Broken link for HTML Help Workshop

### ISSUE THREAD

**Issue by Naheulf** [fantaisie-software/purebasic#149]
The [official link](https://www.microsoft.com/en-us/download/details.aspx?id=21138) to download the `HTML Help Workshop` no longer works (it display a 404 error). However we can still download it from it's archive.org version at https://web.archive.org/web/20210126113408/https://www.microsoft.com/en-us/download/details.aspx?id=21138.

I don't know how to write it in [DocMaker-Help.asciidoc](https://github.com/fantaisie-software/purebasic/blob/devel/AsciiDoc/DocMaker-Help.asciidoc#windows-chm-help) so I let you update this file.

**Comment by tajmone** [comment]
The MS networks of portals and websites is getting worst every day. It's unbelievable that they have so many official documentation pages linking to dead pages.

I've tested downloading via the WayBack Machine and it seems to work, but I wasn't able to download all three resources at once (just the exe installer). We need to check if it's possible to download all three resources, and maybe provide a direct link to each one of them.

So far, I wasn't able to download `HelpDocs.zip` or `htmlhelpj.exe`; I can only get the `htmlhelp.exe` installer, regardless of what I choose. I'm quite sure that if they've archived one asset there'll be also a copy of the others, but the problem is that we'll need to find the correct links (some aspects of the dynamic pages are lost during the archival process).

This might take some time, playing around with different archived snapshots, testing redirection URLs, etc.

**Comment by Naheulf** [comment]
There 3 direct download links on https://web.archive.org/web/20200810052030if_/https://www.microsoft.com/en-us/download/confirmation.aspx?id=21138 if you click on the "click here to download manually" link:
 - [htmlhelp.exe](https://web.archive.org/web/20160301123255/https://download.microsoft.com/download/0/A/9/0A939EF6-E31C-430F-A3DF-DFAE7960D564/htmlhelp.exe) (3.3 MB, English Installer)
 - [HelpDocs.zip](https://web.archive.org/web/20160301123255/https://download.microsoft.com/download/0/A/9/0A939EF6-E31C-430F-A3DF-DFAE7960D564/HelpDocs.zip) (1.3 MB, Doc)
 - [htmlhelpj.exe](https://web.archive.org/web/20160301123255/https://download.microsoft.com/download/0/A/9/0A939EF6-E31C-430F-A3DF-DFAE7960D564/htmlhelpj.exe) (1.4 MB, Japan Installer ?)

Hoverer I don't know why the Japan file is smaller than the English one. Is it only a language pack ?

**Comment by tajmone** [comment]
Well done @Naheulf! These links are good for our use; the WayBack Machine will preserve it's archived contents for ages to come, and since these are old apps they all point to their latest versions.

I'll update the document as soon as I find a free time gap.

> - `htmlhelpj.exe` (1.4 MB, Japan Installer ?)

Ah yes, I forgot that the `htmlhelpj.exe` file is the Japanese version (we definitely won't need that for this project, we can just ignore its link since DocMaker relies on ISO-8859-1 encoding).

> Hoverer I don't know why the Japan file is smaller than the English one. Is it only a language pack ?

Probably it requires `htmlhelp.exe` to be installed, but I've never actually tested it,

**Comment by tajmone** [comment]
@Naheulf, I've fixed the link in PR #151 — a live preview of the amended document can be seen here:

- [`Documentation/DocMaker-Help.html`][DocMaker-Help.html]

I've added a few words about the link redirection (users should know where they're downloading from).

In the end, I've only included the link to the `htmlhelp.exe` installer, because the `helpdocs.zip` file contains copies of the same CHM Help that are part of the **HTML Help Workshop** installation, except for an additional Help for the **HTML Help Viewer** application, which isn't really needed for our goals (and possibly is the same Help found in the viewer app anyway).

Ive omitted linking to `htmlhelpj.exe`, since Japanese is not really of use in this context of the PB Help.

I think that in this case "less is more", and that if we provided the other download links we'd have to add more explanations, just adding confusion with no added benefits for our practical purposes.

What do you think?



[DocMaker-Help.html]: https://htmlpreview.github.io/?https://github.com/fantaisie-software/purebasic/blob/DocMaker-Help/Documentation/DocMaker-Help.html#_windows_chm_help "Live HTML Preview from PR branch"

**Comment by Naheulf** [comment]
> In the end, I've only included the link to the `htmlhelp.exe` installer, because the `helpdocs.zip` file contains copies of the same CHM Help that are part of the **HTML Help Workshop** installation, except for an additional Help for the **HTML Help Viewer** application, which isn't really needed for our goals (and possibly is the same Help found in the viewer app anyway).
> 

Before you say it, I did not notice that these files are present in the installer. The installer contain theses files (I can actually see them with 7-zip) but they are not installed if I use the installer it-self. That why I think you should also include the helpdocs.zip link

> Ive omitted linking to `htmlhelpj.exe`, since Japanese is not really of use in this context of the PB Help.
> 
> I think that in this case "less is more", and that if we provided the other download links we'd have to add more explanations, just adding confusion with no added benefits for our practical purposes.

I agree for the Japanese link since PB does not officially support that language.

**Comment by tajmone** [comment]
> but they are not installed if I use the installer it-self. 

They are installed in a separate folder, as far as I can remember. You should be able to locate them via the file finder tool in File Explorer.

In any case, most of these CHM Help files have to do with how to use CHM files via the WinAPI, or how to customize CHM projects — none of which really affects the DocMaker toolchain. Most of the info they contain doesn't even apply any longer to modern Win OSs, and if end users are interested in working with CHM files, there are still some dedicated websites that offer up to date tutorials and modern tools to fill the gap — but I'd say that's beyond the purpose of our DocMaker Help documentation, which is a tool that lifts all these burdens from PB users anyhow.

Bear in mind that Win 10 doesn't even ship with the **CHM Help Viewer** any longer, and that to install it might actually require some know-how, since MS now discourages the use of CHM Help files, and even blocks them if downloaded from the web.

CHM Help is a legacy format, now replaced in MS Visual Studio by a newer format. Personally, I still like the CHM format, with all its limits (e.g. showing HTML pages emulating IE 7 in the BrowserControl component), but I'm aware that many end users won't be able to open these files today — probably MS is going to soon remove the **CHM Help Viewer** from their downloads too, if they haven't done so already.
