### ISSUE TITLE
Target executable format = console?

### ISSUE THREAD

**Issue by kenmo-pb** [fantaisie-software/purebasic#153]
I noticed that the "Executable format" for all the build targets is set to "Console", rather than default/GUI format.

At first I thought this was a mistake I introduced in #102 , however I checked the history, and the format has been "Console" since the first release on GitHub.

Is this intentional? Is it set to "Console" for a debugging purpose? I find myself always changing it to default/GUI format when compiling a new IDE *from within the IDE*. (The `Makefile` *does not* compile in "Console" format, I believe.)

**Comment by t-harter** [comment]
That sounds like a mistake to me. The "Console" format is pretty useless anyway, so it should not be the default.

**Comment by kenmo-pb** [comment]
OK, I will submit a simple PR. I assume the PB team mostly builds with the makefiles, but this will make it easier to build from within the IDE (without reverting to Console when changing branches).

**Comment by tajmone** [comment]
> The "Console" format is pretty useless anyway, so it should not be the default.

I thought that the "Console" format would add the required components to handle command line parameters, file I/O and streaming to STDIN/OUT, etc., and that applications that can be executed as both CLI and GUI (e.g. DocMaker) would require this setting to support the former.

In other words, that using "Console" is mandatory if the app supports CLI usage, and that it's inclusion doesn't prevent using it as a GUI application.

From what I remember from the Makefiles, some of the compiled tools require Console support, since they are auxiliary tools in the build process.

**Comment by kenmo-pb** [comment]
@tajmone I think @t-harter meant `console` is useless to the final IDE, not all the auxiliary tools. For the IDE, it just seems to open an empty console alongside which never outputs anything.

**Comment by tajmone** [comment]
> @tajmone I think @t-harter meant console is useless to the final IDE, not all the auxiliary tools.

But the IDE also supports CLI parameters at invocation, no? Doesn't that require the "Console" format to be enabled?

> For the IDE, it just seems to open an empty console alongside which never outputs anything.

This should be avoidable.

**Comment by Naheulf** [comment]
> I thought that the "Console" format would add the required components to handle command line parameters, file I/O and streaming to STDIN/OUT, etc., and that applications that can be executed as both CLI and GUI (e.g. DocMaker) would require this setting to support the former.

That require some tests. For me only "streaming to STDIN/OUT"(and STDERR) require a console executable.

**Comment by t-harter** [comment]
> I thought that the "Console" format would add the required components to handle command line parameters, file I/O and streaming to STDIN/OUT, etc., and that applications that can be executed as both CLI and GUI (e.g. DocMaker) would require this setting to support the former.

That is not true. All of this works in a GUI application too (DocMaker is not a console tool). You only really need it if you want your program to be usable inside an existing console and not opening a new console window when you use the OpenConsole() command in PB. All that is Windows only as well. On Linux/Mac the setting has no effect at all beyond causing the IDE to run the program in a terminal. The final executable is not affected by the setting at all there.

I doubt many people write true console programs on Windows. So it definitely should not be the default setting.

**Comment by tajmone** [comment]
Thanks for the clarification @t-harter! In the Help Documentation, I've always found the definition of what's a "console application" a bit unclear. The misleading part is the following sentence in the [OpenConsole()](https://www.purebasic.com/documentation/console/openconsole.html) documentation:

> If you want to create a standard console application, like 'dir', 'del' etc. you must compile the executable using the 'Console' format

According to other statements in that page, using any commands from the Console lbrary requires to compile the app as "Console", which include commands like `PrintN()`, so I assumed that if a GUI application also allow CLI invocation and printing some text to the console (e.g. version info via `--version`, or CLI help via `-h`) it would necessarily have to be compiled as "Console".

Maybe the Help Docs could be improved on this aspect, covering more the difference between pure Console apps and hybrid ones.

**Comment by t-harter** [comment]
Yes, the docs could be improved in this regard.

To see the effect, open a `cmd.exe` and run the following from it: `PureBasic.exe /?`

You will briefly see a second console window appear and then disappear but nothing is written in the `cmd.exe` window. That is because the IDE is compiled as a GUI application. Opening a console from that will always be in a separate window (not the parent console). But you can still pass commandline parameters to it and I think pipes should work as well but I am not 100% sure.

Now if you compile the IDE in Console mode then this part will work correctly. BUT if you launch the IDE as a regular GUI application now (not from `cmd.exe`) then it will now also open a separate console window which will just sit there empty and closing it will kill the IDE. That is what the console switch does which makes it so useless. It is why some windows tools come in separate "console" and "gui" variants because this is a compile-time setting.

(I think it is possible with more modern API functionality to use to the parent `cmd.exe` console without compiling as a console application but our console library does not do that and I have not looked into it more closely).

**Comment by kenmo-pb** [comment]
Yes, sorry for any added confusion. To summarize:

- The **default** for a new file/project is **GUI mode** (called "Windows" in the dropdown, when on Windows)
- For some reason, the format within the IDE project's PBP file got set to **Console**
- When I added more project targets in PR #102 I duplicated the **Console** setting to them all
- The `makefile` (which I think is the "definitive" IDE build) compiles in **GUI mode**
- Of course **GUI mode** can receive commandline parameters just like **Console mode**
- This discussion pertains to building the IDE, not the other auxiliary tools

See the PBP edits in PR #157 

> I doubt many people write true console programs on Windows.

I just started another Windows console-mode project this week! :grin:

**Comment by tajmone** [comment]
> > I doubt many people write true console programs on Windows.
> 
> I just started another Windows console-mode project this week! 😁

I also use PB to create console applications. But I think that what @t-harter meant by "true console programs", in that context, would be those apps that leverage the terminal (or its emulator) to create a full user interface with menus, tabs, split views, etc. — in other words, applications like the first editors and apps from the DOS era, which today will require libraries like **Curses** to be created, but for which PureBasic offers the "graphical console" mode, which allows to control cursor positioning, colors, etc.

I always had trouble understanding the differences between a PB console app becomes a "graphical console" app, but I know that using certain commands from the Console library will turn it to the latter, and that when this happens some functionality (e.g. piping) won't work as expected. I have never used the graphic console modality, just the plain one to allow me to create binary CLI tools and new CMD/Shell commands.
