### ISSUE TITLE
HTTPS change broke project file detection

### ISSUE THREAD

**Issue by kenmo-pb** [fantaisie-software/purebasic#22]
The universal replacement of HTTP links to HTTPS has broken project file (PBP) detection.

Since commit #10 the ProjectManagement.pb now sets a PBP's namespace to HTTPS, and also expects HTTPS when opening a project.

If an older PBP file is opened in the new IDE, or a newly saved PBP file is opened in an earlier IDE, it is not recognized as a project, but instead opened as an XML file.

See IsProjectFile() and related.

**Comment by tajmone** [comment]
> The universal replacement of HTTP links to HTTPS has broken project file (PBP) detection.

That's rather strange, that commit was about changing only URLs to PureBasic and SpiderBasic websites, not general HTTP protocol handling.

It basically touched only links in Markdown documents, references in source comments and maybe a couple of links in "About" dialogs, etc.

Thanks for reporting this, I'll try to dig which is the culprit line.

Under which OS are you experiencing the problem?

**Comment by tajmone** [comment]
I think that the problem might be due to changes in the [`PureBasicIDE/ProjectManagement.pb`][ProjectManagement.pb] file, it contains a variety of XML namespace operations (see diff in link).

> If an older PBP file is opened in the new IDE, or a newly saved PBP file is opened in an earlier IDE, it is not recognized as a project, but instead opened as an XML file.

Ideally, new versions of the IDE should always use HTTPS, but also allow HTTP, but this would require refactoring the code, so tomorrow I'll take same time to revert the HTTPS changes in actual code.

But IMO, future versions of the IDE should only use the secure protocol wherever possible (and those domains do support it, but the code apparently not).

[ProjectManagement.pb]: https://github.com/fantaisie-software/purebasic/pull/10/files#diff-239d629c6fd2a93c09264b82ba4d2df8L1302

**Comment by kenmo-pb** [comment]
I saw it on Windows 10, but I'm actually setting up a build environment on Windows 7 right now too, I'll verify again.

Look at ProjectManagement.pb lines 160, 178, 828, 1302, 1325.
Validating a PBP file does some hard compares against the URL string, which used to be HTTP.

My recommendations:

1. For backwards compatibility with older IDEs, keep *writing* `http://` to PBP files.
2. For future-proofing, *reading* PBP files should accept `http://` or `https://` - or just ignore the protocol.
3. The string is hard-coded in many places - it should become a named constant.
4. Because the URL might be used elsewhere in the IDE with HTTPS, it should probably be a separate constant clearly intended as a namespace (`#ProjectFile_NamespaceURL` or something).

I can submit a patch once I'm up and running on this system.

(I see you replied while I was writing this)

**Comment by tajmone** [comment]
I should be able to push a fix in a short while, there's only that file and the PBP file which seem to be need fixing. If I push the commit on a dev branch, could you please confirm to me that the problem is gone?

I can't compile the PB IDE on my machine to due incompatibility with my system setup (I hand't had time to set up a virtual machine for this).

**Comment by tajmone** [comment]
Ok @kenmo-pb, I've created the `https-fix` branch and pushed a commit that hopefully should fix this:

https://github.com/fantaisie-software/purebasic/tree/https-fix

From a quick look at the changed files, three PB sources stood out as being possibly the ones affected by those changes. In all other sources the changes only affected comments. 

There was one file which I didn't change [`PureBasicIDE/CompilerFlags.pb`][CompilerFlags.pb] (LL 54, 64, for it doesn't seem related to the above mentioned problem:

```purebasic
CompilerIf #SpiderBasic
  #ProductName$ = "SpiderBasic"
  #ProductWebSite$ = "https://www.spiderbasic.com"
  
  #SourceFileExtension  = ".sb"
  #IncludeFileExtension = ".sbi"
  #ProjectFileExtension = ".sbp"
  #FormFileExtension    = ".sbf"
  
  #CatalogFileIDE = "SB_IDE"
CompilerElse
  #ProductName$ = "PureBasic"
  #ProductWebSite$ = "https://www.purebasic.com"
  
  #SourceFileExtension  = ".pb"
  #IncludeFileExtension = ".pbi"
  #ProjectFileExtension = ".pbp"
  #FormFileExtension    = ".pbf"
  
  #CatalogFileIDE = "PB_IDE"
CompilerEndIf
```

If I've understood correctly, these constants should affect the link to the website shown to end users in various dialogues — which is what the original commit was intended to fix, for you don't want them to visit the website via the unsafe protocol, since they might be demo users deciding to buy a license, so they should be directed via HTTPS!

Could you confirm to me if this fixes the problem? I can then create a pull request for it.

Anyhow, the use of insecure HTTP protocol needs to be addressed in the future.

[CompilerFlags.pb]: https://github.com/fantaisie-software/purebasic/blob/master/PureBasicIDE/CompilerFlags.pb#L54

**Comment by tajmone** [comment]
@fantaisie-software, do you think that keeping the HTTPS change in [`CompilerFlags.pb`][CompilerFlags.pb] is going to be OK? i.e. the `#ProductWebSite$` is used only to provide end-user links to the website(s) and not for internal code tasks (like the XML problem above)

[CompilerFlags.pb]: https://github.com/fantaisie-software/purebasic/blob/master/PureBasicIDE/CompilerFlags.pb#L54

**Comment by fantaisie-software** [comment]
Yes, should be OK.

**Comment by tajmone** [comment]
Great then! When someone confirms that the bug reported by @kenmo-pb is solved then the branch can be merged into `master`. (no need for a PR, since in it's already in the main repo 😉)

**Comment by tajmone** [comment]
PS: I'm sorry for the inconvenience, didn't realize that changing the HTTP in those sources would break compatibility. 

As mentioned, I haven't currently managed to setup a build environment on my local machine, I have to solve some conflicts first, so in the meantime I'm not able to actually build the IDE from scratch. Should be able to handle this soon.

**Comment by kenmo-pb** [comment]
Good news and bad news.

Good news, your patch compiles and fixes the PBP problem. Now it writes and reads "http://" again which works with the 5.71 LTS IDE.

Bad news, the Check For Updates feature is broken, for essentially the same reason. See `UpdateCheck.pb` line 138.

        If ResolveXMLNodeName(*AllVersions, "/") = #ProductWebSite$ + "/namespace/versions"

When it checks the XML file at `https://www.purebasic.com/versions.xml` it verifies the namespace. Here it does use a named constant, not a string literal. But that constant has been changed to HTTPS, the check fails, and I get "Could not retrieve information about new updates".

Again, a new namespace constant (which remains HTTP for now) would solve it.

**Comment by tajmone** [comment]
Thanks @kenmo-pb. I'll fix that too then.

I was hoping that the `#ProductWebSite$` would be used only to redirect the user to the website. The problem I can envision is the following scenario:

- A user ears about PB, googles it up and finds the website. The icon in the URL bar shows that the website is safely using HTTPS.
- He/she downloads the PB demo version and starts using it.
- At a certain point he/she decides to buy a license, opens the About dialogue to quickly access the website URL and ... he/she's redirected to the website via an insecure connection, right when it's time to use the credit card!

That's as bad as it can get! 

Needless to say, if the user is the careful type, he/she might even get suspicious (or paranoid) about an HTTPS enabled website that redirects you via plain old HTTP from it's software links. I put myself in that situation, and if I weren't the wiser I'd get suspicious about it.

Non HTTPS connections are unthinkable on a commercial site at transactions time.

Anyhow, one thing at the time. Now I'll reverse the changes on that last file too, and hopefully the maintainers in the future would come up with a solution to this — if not changing the XML namespace, at least use a different constant (or add the `s` at use time) for links to the websites.

**Comment by tajmone** [comment]
OK, I've amended the previous commit and force pushed to the branch (so we have a single commit to fix the problem).

I've reverted the two occurrences of `#ProductWebSite$` in `CompilerFlags.pb` (and left the HTTPS fix in the comment link).

This effectively reverts all substitutions to real code (preserving the HTTPS fix inside comments, so if users copy and paste them in the browser they'll end up in the forum using the safe protocol).

One last confirmation from all?

Thanks for your help @kenmo-pb!

PS: Next week I'll take a day to work out how to setup the build toolchain on my machine, hopefully without having to resort to a virtual machine.

**Comment by kenmo-pb** [comment]
Hi, you can also take a look at PR #23 I just submitted.
It too keeps HTTPS in web links, and reverts to HTTP for namespaces, with the added benefit of named constants (hopefully acceptable names).

Side note: sorry if I do anything out of order, or bad GitHub etiquette. I am not new to using Git, but I am new to collaborative pull requests via GitHub!

**Comment by tajmone** [comment]
@kenmo-pb, thanks for this PR, it's really helpful.

I'm a just a Collaborator, so I can't take the liberty to merge into `master` branch, but only work on dev branches.

> Side note: sorry if I do anything out of order, or bad GitHub etiquette. I am not new to using Git, but I am new to collaborative pull requests via GitHub!

Your contributions are excellent, well detailed and helpful. As for the "collaborative ethos", I guess that this being a young project it's all in the making, and ultimately its collaborative standards will be shaped around real users interactions, rather than theory.

Pull requests are a GitHub thing, not really part of Git, and they add a layer of complication (for example, pulling a PR branch locally requires some acrobatics). 

Ideally this project will be heading toward creating Teams of collaborators around an Organization (see #18 on this), which makes it easier for all participants to view and participate to each others' contributions thanks to dev branches which are part of the same repository. Also, Collaborators get access to the full Dashboard functionality (labels, milestones, and [automated kanban Projects with reviews and bugs triage]) which are real time savers and allow great coordination and leaving behind a clean history.

But that's rushing ahead of time and needs! — let's wait and see how the collaborative effort shapes itself naturally. We are a well established community, thanks to the PB Forums, so two thirds of the job are already accomplished (trust and long-term cooperation in one way or another). It's just that Git comes as a new thing into the online PB community, so it might require some time and adjustments for a consolidated community to gradually embrace a new tool (and I'd say, not the easiest or friendlier tool either), and it's only reasonable to expect to some resistance to change. 

[automated kanban Projects with reviews and bugs triage]: https://help.github.com/en/github/managing-your-work-on-github/about-project-boards

**Comment by kenmo-pb** [comment]
Two specific things I didn't know:

1. When I created that pull request, should I have selected the upstream's "master" branch? (I did.) Or a different branch?

2. If someone else has a Pull Request open (your HTTPS fix) and I want to add to it (change literals to constants, for example) what's the best way to do that? This time, I just created my own branch "namespaces-fix" and PR'ed that, which felt like a duplicate of your work, or stealing your credit!

**Comment by tajmone** [comment]
> When I created that pull request, should I have selected the upstream's "master" branch? (I did.) Or a different branch?

You can create a PR to any branch you wish, and it's common for many repositories to actually work on a `devel` branch and only merge into `master` when a new release is out, so that the `master` is always kept clean, with each commit matching a tagged release.

Repository owners should be able to merge into a different branch than the one you proposed (but this might depend on the repository configuration).

> If someone else has a Pull Request open (your HTTPS fix) and I want to add to it (change literals to constants, for example) what's the best way to do that? This time, I just created my own branch "namespaces-fix" and PR'ed that, which felt like a duplicate of your work, or stealing your credit!

In this specific example (the HTTPS fix branch) you're dealing with a branch present in the upstream repository, so you can do with it anything you'd do to normal branches. But if it was a pull request coming from a fork repository, than you'd have to go through some pains to pull that user's branch locally and be able to edit it:

- https://github.com/TeamPorcupine/ProjectPorcupine/wiki/How-to-Test-a-Pull-Request

Since you'd be editing the contents of the fork repository, you'd have to submit a PR to the fork, and after the fork owner merges your PR into his branch and pushes upstream then your changes would become part of the original PR upstream. This creates an entangled triangulation between you _origin_, the PR creator fork remote repository, and the _upstream_ original repository where all changes are destined.

This is why I asked for a Collaborator role in this repo, in order to be able to make PR directly from branches in the upstream repository, which are easier to pull locally by all participants, and even edit them in group. Of course, this removes the whole concept of working in isolated forks, where each fork owner has ultimate control over his*her own code, but since we are small group this makes things easier and there aren't real risks of stepping on each other's toes as long as participants agree on who should be editing what and whether forces pushes are allowed or not.

**Comment by kenmo-pb** [comment]
Got it, thanks for the help! Maybe we should set up an upstream development branch going forward, and pull into that. (Then merge to `master` only when released? - I have seen projects which do that.)

This XML namespace issue should be OK going forward, so I'll close this issue. Solved by PR #23

**Comment by tajmone** [comment]
@kenmo-pb, it looks like your PR #23 also included my HTTPS to HTTP rollbacks from this branch, effectively fixing the original problem for which this Issue was opened as well as adding your improvements.

So, if you can confirm this, I could safely delete this branch for there's no longer the need to merge it into `master`, for you PR took care of its fixes.

**Comment by kenmo-pb** [comment]
Yes, my PR included the HTTP rollback for Project File and Update Check namespaces. It keeps HTTPS for the website presented to the user elsewhere. And both are now separate named constants for future clarity in the code.
