### ISSUE TITLE
Use Windows 10 SDK

### ISSUE THREAD

**Issue by ChrisRfr** [fantaisie-software/purebasic#32]
I added Windows 10 SDK support in Window-x64(x86).cmd
They support now both Windows SDKs, following:
. Set USE_SDK10=True  (Win 10 SDK)
. Set USE_SDK10=False (Win 7.1 SDK)

In case of space in PUREBASIC_HOME path, It is possible to use the short path:
Set PUREBASIC_HOME=C:/PROGRA~1/PureBasic
In this case, we must run this batch as Administrator to have full control. I added a control on rights.

Window-x64.cmd
```
@Echo off
Cd /D %~dp0

:: Set the PureBasic home directory to a real x64 PureBasic installation
:: Warning:
::   Use a Path Without Space
::   When compiling, the IDE will be Overwriten with the new one
::   If you use C:/PROGRA~1/PureBasic short path (C:/Program Files/PureBasic). You Must run this batch as Administrator to have full control
Set PUREBASIC_HOME=C:/PROGRA~1/PureBasic
::Set PUREBASIC_HOME=E:/PureBasic/Portable/PureBasic_5.71_x64

Echo. > "%PUREBASIC_HOME%/Tmp_FullAccess"
If Exist "%PUREBASIC_HOME%/Tmp_FullAccess" (Del /q /f "%PUREBASIC_HOME%\Tmp_FullAccess") Else (Echo Run this batch as Admin to have full control on PUREBASIC_HOME path && Echo. && Pause && Goto End)

:: USE_SDK10=True for using Microsoft 10 SDK (Check SDK10_VERSION) / USE_SDK10=False for using Microsoft 7.1 SDK
Set USE_SDK10=True

Set PB_PLATEFORM_SDK=C:/Program Files/Microsoft SDKs/Windows/v7.1
Set PB_PLATEFORM_SDK10=C:/Program Files (x86)/Windows Kits/10
Set SDK10_VERSION=10.0.18362.0

Set PB_VS8=C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC
Set PATH=%PB_VS8%/bin;%PATH%
Set PATH=%PB_VS8%/bin/x86_amd64;%PATH%

:: Path to Make and dependencies from UnxUtil (cp.exe,make.exe,pwd.exe,rm.exe,touch.exe,zip.exe)
:: or Path to Make and dependencies from Gnuwin32 (bzip2.dll,cp.exe,libiconv2.dll,libintl3.dll,make.exe,pwd.exe,rm.exe,touch.exe,zip.exe). Here extracted, in Bin subfolder
::Set MAKE_PATH=%CD%/UnxUtils/usr/local/wbin
Set MAKE_PATH=%CD%/Bin
Set PATH=%MAKE_PATH%;%PATH%

Set PB_LIBRARIES=%CD%/Libraries
Set PB_BUILDTARGET=%CD%/Build/x64

Set PB_PROCESSOR=X64

Set PATH=%PUREBASIC_HOME%/Compilers;%PATH%

If %USE_SDK10%==False (
  Set PB_VC8_ANSI=cl.exe -I"%PB_VS8%/include" -I"%PB_LIBRARIES%" -DWINDOWS -DVISUALC -DX64 -DPB_64 -D_USING_V110_SDK71_ -I"%PB_PLATEFORM_SDK%/Include" -I"%PB_PLATEFORM_SDK%/Include/crt" -I. /nologo /GS- /D_CRT_NOFORCE_MANIFEST
  Set PB_LINKER=link /LIBPATH:"%PB_PLATEFORM_SDK%/Lib/x64" /LIBPATH:"%PB_VS8%/Lib/amd64"
)
If %USE_SDK10%==True (
  Set PB_VC8_ANSI=cl.exe -I"%PB_VS8%/include" -I"%PB_LIBRARIES%" -DWINDOWS -DVISUALC -DX64 -DPB_64 -I"%PB_PLATEFORM_SDK10%/Include/%SDK10_VERSION%/ucrt" -I"%PB_PLATEFORM_SDK10%/Include/%SDK10_VERSION%/shared" -I"%PB_PLATEFORM_SDK10%/Include/%SDK10_VERSION%/um" -I. /nologo /GS- /D_CRT_NOFORCE_MANIFEST
  Set PB_LINKER=link /LIBPATH:"%PB_PLATEFORM_SDK10%/Lib/%SDK10_VERSION%/ucrt/x64" /LIBPATH:"%PB_VS8%/Lib/amd64"
)

Set PB_VC8=%PB_VC8_ANSI% -DUNICODE
Set PB_NASM=nasm.exe -DWINDOWS -fwin64 -O3
Set PB_LIBRARIAN=lib /nologo
Set PB_LIBRARYMAKER="%PUREBASIC_HOME%/SDK/LibraryMaker.exe" /NOLOG /COMPRESSED /CONSTANT WINDOWS /CONSTANT %PB_PROCESSOR%
Set PB_IOFIX=
Set PB_OGREFLAGS=/MT /O2

Set PB_OGRELIBRARIAN=lib /NOLOGO
Set PB_WINDOWS=1
Set PB_OBJ=obj
Set PB_LIB=lib

:: Set a default subsystem
Set PB_SUBSYSTEM=purelibraries/

Echo.
Echo Setting Environment for PureBasic %PB_PROCESSOR%
Echo.
Echo Type: Make to Compile all the Dependencies and the IDE
Echo.

Cd PureBasicIDE
:: If we don't specify any args, we want to open a CMD. Else we can use this script to setup an env for batching
If [%1]==[] Goto OpenCmd

Goto End

:OpenCmd
cmd

:End
```

Window-x86.cmd
```
@Echo off
Cd /D %~dp0

:: Set the PureBasic home directory to a real x86 PureBasic installation
:: Warning:
::   Use a Path Without Space
::   When compiling, the IDE will be Overwriten with the new one
::   If you use C:/PROGRA~2/PureBasic short path (C:/Program Files (x86)/PureBasic). You Must run this batch as Administrator to have full control
Set PUREBASIC_HOME=C:/PROGRA~2/PureBasic
::Set PUREBASIC_HOME=E:/PureBasic/Portable/PureBasic_5.71_x86

Echo. > "%PUREBASIC_HOME%/Tmp_FullAccess"
If Exist "%PUREBASIC_HOME%/Tmp_FullAccess" (Del /q /f "%PUREBASIC_HOME%\Tmp_FullAccess") Else (Echo Run this batch as Admin to have full control on PUREBASIC_HOME path && Echo. && Pause && Goto End)

:: USE_SDK10=True for using Microsoft 10 SDK (Check SDK10_VERSION) / USE_SDK10=False for using Microsoft 7.1 SDK
Set USE_SDK10=True

Set PB_PLATEFORM_SDK=C:/Program Files/Microsoft SDKs/Windows/v7.1
Set PB_PLATEFORM_SDK10=C:/Program Files (x86)/Windows Kits/10
Set SDK10_VERSION=10.0.18362.0

Set PB_VS8=C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC
Set PATH=%PB_VS8%/bin;%PATH%

:: Path to Make and dependencies from UnxUtil (cp.exe,make.exe,pwd.exe,rm.exe,touch.exe,zip.exe)
:: or Path to Make and dependencies from Gnuwin32 (bzip2.dll,cp.exe,libiconv2.dll,libintl3.dll,make.exe,pwd.exe,rm.exe,touch.exe,zip.exe). Here extracted, in Bin subfolder
::Set MAKE_PATH=%CD%/UnxUtils/usr/local/wbin
Set MAKE_PATH=%CD%/Bin
Set PATH=%MAKE_PATH%;%PATH%

Set PB_LIBRARIES=%CD%/Libraries
Set PB_BUILDTARGET=%CD%/Build/x86

Set PB_PROCESSOR=X86

Set PATH=%PUREBASIC_HOME%/Compilers;%PATH%

If %USE_SDK10%==False (
  Set PB_VC8_ANSI=cl.exe -I"%PB_VS8%/include" -I"%PB_LIBRARIES%" -DWINDOWS -DVISUALC -DX86 -D_USING_V110_SDK71_ -I"%PB_PLATEFORM_SDK%/Include" -I"%PB_PLATEFORM_SDK%/Include/crt" -I. /nologo /arch:IA32 /GS- /D_CRT_NOFORCE_MANIFEST /D_USE_32BIT_TIME_T
)
If %USE_SDK10%==True (
  Set PB_VC8_ANSI=cl.exe -I"%PB_VS8%/include" -I"%PB_LIBRARIES%" -DWINDOWS -DVISUALC -DX86 -I"%PB_PLATEFORM_SDK10%/Include/%SDK10_VERSION%/ucrt" -I"%PB_PLATEFORM_SDK10%/Include/%SDK10_VERSION%/shared" -I"%PB_PLATEFORM_SDK10%/Include/%SDK10_VERSION%/um" -I. /nologo /arch:IA32 /GS- /D_CRT_NOFORCE_MANIFEST /D_USE_32BIT_TIME_T
)

Set PB_VC8=%PB_VC8_ANSI% -DUNICODE
Set PB_NASM=nasm -DWINDOWS -fwin32 -O3
Set PB_LINKER=polink
Set PB_LIBRARIAN=polib
Set PB_LIBRARYMAKER="%PUREBASIC_HOME%/SDK/LibraryMaker.exe" /NOLOG /COMPRESSED /CONSTANT WINDOWS /CONSTANT %PB_PROCESSOR%
Set PB_IOFIX="/D__iob_func=__p__iob" /D_gmtime32=gmtime /D_mktime32=mktime
Set PB_OGREFLAGS=/MT /O2

Set PB_OGRELIBRARIAN=lib /NOLOGO
Set PB_WINDOWS=1
Set PB_OBJ=obj
Set PB_LIB=lib

:: Set a default subsystem
Set PB_SUBSYSTEM=purelibraries/

Echo.
Echo Setting Environment for PureBasic %PB_PROCESSOR%
Echo.
Echo Type: Make to Compile all the Dependencies and the IDE
Echo.

Cd PureBasicIDE
:: If we don't specify any args, we want to open a CMD. Else we can use this script to setup an env for batching
If [%1]==[] Goto OpenCmd

Goto End

:OpenCmd
cmd

:End
```
Let me know if it's not the right way to do it.

**Comment by tajmone** [comment]
Thanks a lot! This was much needed!

I'll try it and let you know.

**Comment by tajmone** [comment]
@ChrisRfr, which MSVC compiler was the script written for?

I've tried tweaking it to my own machine setting using **MS Visual C++ Build Tools 2019**, but didn't manage to compile all the way through due to paths differences — but the scripts are a good breakthrough for the Win10 SDK part and the rest are already in place.

I was experiencing some problems with paths that used backslashes, so I had to replace all occurrences of `%CD%` with forward-slashed absolute paths.

Below I'll share some general considerations which might be worth keeping in mind.

## Paths Differences Between MSVC and VC Build Tools

Depending on whether users installed the full Visual Studio or just the Build Tools, installation paths may vary. For example, on my machine the `bin` folder of the VC 2019 Build Tools:

    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.23.28105\bin\Hostx64\x64

The presence of the `BuildTools` folder seems to suggest that probably the path to the `bin` folder of the full Visual Studio 2019 is different.

As mentioned, I've installed the VC 2019 tools only because of [Rust] and [Nim] langs, so I don't really use it much by itself. But from the little that I've read, I think that all the MSVC editions (whether it's the full VStudio or just the CLI Tools) provides a folder with some batch scripts to correctly setup the CMD environment for the intended target build (x86/64, etc.). The folder is usually called `VC\Auxiliary\Build\` and contains some batch scripts like these:

- `vcvars32.bat`
- `vcvars64.bat`
- `vcvarsall.bat`
- `vcvarsamd64_x86.bat`
- `vcvarsx86_amd64.bat`

I remember seeing the same CLI system in VS 2010, which I had installed to compile C libraries for PureBasic.

In this regard, see the article on Microsoft Docs:

- [Use the Microsoft C++ toolset from the command line]

I think that running these auxiliary scripts could simplify the IDE build, for they should already setup the environment so that the correct compiler and linker are already on the PATH, along with the headers `include` folders, etc.

Also these scripts should work regardless of any updates and how these might affects folder names in the paths.

## Win10 SDK

I've noticed that Win10 SDK folder in `C:\Program Files (x86)\Windows Kits\10\Include\` contains the following subfolders:

    10.0.18362.0
    10.0.17763.0
    10.0.17134.0
    10.0.16299.0

At first glance, they seem to relate to Win 10 updates, for their contents are mostly similar. I was wondering if updates to Win 10 add new paths, and whether using direct absolute paths to the `Include` is a good strategy.

# Questioning the Approach

The big question is How many build scripts are we going to create? Since users who have already installed a given SDK version (7 or 10) will be stuck with it and have to install a MSVC that matches it; and because some users might have already installed a full Visual Studio version and might have to install the VC Build Tools; in the end there are quite a number of possible combinations of VC compilers and Win SDKs, leading to a script that would need to handle all the different absolute paths (which might also change with product updates).

I'm starting to wonder, after seeing all these complications, if this is the right approach. All these acrobatics are being done just to bend the MS tools to build using GNU Make, whereas the MS way of doing this is using solution files.

Besides, the Makefile itself doesn't do any high magic that couldn't be achieved via a simple script or, even better, a small PB application — it just invokes the compilers (PB/C) with switches, does some file system operations, and other stuff that doesn't strictly require using Make.

In any case, I think that using [CMake] would allow to reduce the number of build scripts by offering a single build file able to handle all operating systems and different compilers. It was created for this very purpose, abstracting away from end users all the nitty gritty of these machine specific differences, in order to provide a single solution which will generate the user specific configuration required by the user machine. CMake is a very powerful tool (much better than using only Make), offering end users a simple-to-use graphic interface which allows a quick usage experience.

That, or creating PB app which is able to handle building the IDE cross platform, allowing end users to specify which compiler and SDK to use. At least, a PB app would be less of a deterrent for users who don't like to get their hands dirty with C stuff (which is often the reason why they chose PureBasic).

What I don't understand is why the precompiled binaries can't be simply included here. The IDEs have to be build with every new PB and SB release, to create the distribution packages, so this repo could include always the latest C precompiled (which probably won't even change with every new PB version). This would allow the C compilation part to be optional, and allow end users to focus on the PB part of the project (which is what attracts us here in the first place).



[CMake]: https://cmake.org/
[Rust]: https://www.rust-lang.org
[Nim]: https://nim-lang.org

[Use the Microsoft C++ toolset from the command line]: https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=vs-2019

**Comment by ChrisRfr** [comment]
> I was experiencing some problems with paths that used backslashes, so I had to replace all occurrences of %CD% with forward-slashed absolute paths.

I've replaced %CD% by %~dp0 in the 2 batches 
%cd% refers to the current working directory (variable) %~dp0 refers to the full path to the batch file
I also added some controls to check the path variables

For Microsoft Visual Studio,
I use the 2013 version as writen. I tried with version 2019 but without success
It is already well with Microsoft SDKs 7.1 or 10

Newest Window-x64(x86).cmd are in my fork here https://github.com/ChrisRfr/purebasic
and I added a Bin folder with the required Gnuwin32 tools with their licenses

**Comment by tajmone** [comment]
> For Microsoft Visual Studio, I use the 2013 version as writen. 

Thanks (I couldn't find the version, must have missed it).

> I tried with version 2019 but without success

Good to know, I'll stop wasting time  on it then. I can install the Build Tools for 2013 along 2019 without problems (as far as I know), and since the SDK is already installed it won't be a huge install either.

**Comment by tajmone** [comment]
> I uploaded on my fork the required Gnuwin32 tools to compile all the dependencies and the IDE. I've included the licence files. All are grouped in a new Bin folder
> 
> https://github.com/ChrisRfr/purebasic/tree/master/Bin
> 
> They're a little outdated (less than UnxUtils) but they do the job

This is much better! now we have the tools with the licenses, not from the jurassic era, and only what's needed.

> Thus, in Window-x64(x86).cmd,
> 
>     Set PATH=%~dp0\Bin;%PATH%
> 
> is sufficient, no need to download and use UnxUtils anymore

No need, Win users can download this package instead, from the project Wiki, so we don't pollute the repository with binary files (especially unneeded files by users from other OSs).

I think we'll have to create two separate Zip files, one without the common Bash commands (for those who have Bash because of Git, which is the majority of users) and another one (or a supplement?) for those who don't have Bash (and neither Git).

The script could also offer end users the option to download the zip package via cURL, which now ships natively with Win 10, but then I'm not sure about older versions like 7 and 8 (no one still uses Vista, I hope). If not, cURL becomes only a further complication (of course, the Git Bash also includes  cRUL, actually a better version from MS cURL, which is feature-incomplete).

Today I might not find the time, but when I have some spare time out the frenzy of these pre-festivity days I'll add your branch to my workflow so I can join in on experimenting with the script (right now I've just been pasting it from this Issue).

**Comment by tajmone** [comment]
I can't believe it! MSVC 2013 is not available as Build Tools distribution! Only the full MSVS IDE can be downloaded...

* [MS Redistributables and Build Tools donwload page](https://visualstudio.microsoft.com/vs/older-downloads/#visual-studio-2015-vc-redistributable-family)

That's bad news. Having to go through all these pains of compatibility versions, MS IDEs and packages that fail to install under MS Windows, and having to install a whole IDE just for the compiler, linker, debugger and some header files!

And then Microsoft has just announced that it's going to rewrite all the core parts of Windows (present and past) in Rust (or a Rust-like language) because C and C++ are fundamentally two _unsafe languages_, with their "undefined behaviours" allowing dangling pointers and reuse of freed memory being the root cause behind all the security holes and bugs you find in all software: 

- [Microsoft: We're creating a new Rust-like programming language for secure coding]

Ten years ago they were still fighting the browsers-war against Mozilla, and now they're adopting Mozilla's child-lang to save the boat from sinking. Amazing how things turn out (as if no sound minded person ever warned us about the intrinsic problems of C and C++)

And not only Microsoft, even Linux distros have started re-writing the Kernel and other core-parts in Rust (especially since the vulnerabilities that popped up in the last three years, like [Dirty COW] and others).

Of course, in Rust you'd never suffer any of these set-up pains (and it's cross platform in the widest sense you could think of, since it can compiler to almost any microchip you could image of, from your fridge to the toaster, _literally_).

I just hope that in 10 years time all this will be remembered as "the Dark Ages of coding history", and that I might live enough to enjoy the satisfaction of that day. An era were OOP is delegated to the "Trivia of history"! It's coming soon... stay tuned.



[Microsoft: We're creating a new Rust-like programming language for secure coding]: https://www.zdnet.com/article/microsoft-were-creating-a-new-rust-based-programming-language-for-secure-coding/
[Dirty COW]: https://dirtycow.ninja/

**Comment by tajmone** [comment]
## Wiki Updated

I've adde to the Wiki a section about building the IDE using Win 10 SDK:

- [Wiki » Building on Windows](https://github.com/fantaisie-software/purebasic/wiki/Building-on-Windows#windows-10-sdk)
