### ISSUE TITLE
Forums bugs

### ISSUE THREAD

**Issue by fantaisie-software** [fantaisie-software/purebasic#65]
Should we put them here in issues, for a better overview ? May be one issue per bug, with a link to the forum thread ?

**Comment by tajmone** [comment]
> Should we put them here in issues, for a better overview ? May be one issue per bug, with a link to the forum thread ?

Maybe only the IDE related bugs should go here.

As for the compiler/language, I suggest opening a repository dedicated to bugs and features requests, using just issues. It's quite a common practice on GitHub, even for commercial closed-source products. For example, Sublime Text tracks bugs reports via GitHub (only, it doesn't use the forum for bugs tracking at all):

https://github.com/sublimehq/sublime_text

**Comment by NicolasGoeddel** [comment]
Sounds like a wonderful idea.

**Comment by fantaisie-software** [comment]
Yes, my suggestion was only for IDE related bugs indeed.

**Comment by tajmone** [comment]
### Add Issue Templates

When I have some time in the upcoming days I'll create a PR to add [issue templates], one for reporting IDE bugs and the other one for features requests.

- [ ] Add Issue templates:
    + [ ] PB IDE Bug report
    + [ ] PB IDE Feature request

This way we can provide a boilerplate with the required info and format to file a bug report or feature request, the former being very useful (especially with users not acquainted with GitHub workflow) to ensure that all the required info is included (PB version, OS, architecture, etc.).

Besides, these are very practical for they present the user with a list of choices to select from, when he/she opens a new issue.

Also, this system is going to be extremely useful when (in the future) the project will also include other PB related projects besides the IDE (e.g. the SDK, Documentation, etc.), for it will allow clear separation of Issues at creation time, thanks to the fact that issue templates can also associate the right labels to the created issues.

So, we can start by assigning the <kbd>[PB IDE]</kbd> label to both templates (and <kbd>bug</kbd> or <kbd>feature request</kbd>, accordingly) so that, when new sub-projects will be added in the future, the old Issues will already be associated to the PB IDE, and we'll be able to create new Issue templates for the SDK, Documentation, etc.




[issue templates]: https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates

[PB IDE]: https://github.com/fantaisie-software/purebasic/labels/%3Agear%3A%20PB%20IDE "View PB IDE label"

**Comment by tajmone** [comment]
@fantaisie-software, I've been reading through the documentation on [GitHub Issues templates] and realized that only the repository owner can create multiple Issue templates (requires access to the <kbd>Settings</kbd> menu).

I originally thought that I could [manually add the Issue templates] via a normal commit, but this feature is now considered «legacy» and only allows a single template, furthermore it seems to use a different format from the new system for Issue templates.

So, it looks like you'll have to handle this yourself.

As mentioned previously, I suggest creating a "Bug report" and "Feature request" templates specifically targeting the __PureBasic IDE__ (and maybe separate templates for the __PureBasic Debugger__), automatically assigning the required labels. Also, I suggest adding a blank template for general issues.

From what I read, the <kbd>Settings</kbd> » <kbd>Features</kbd> » <kbd>Issues</kbd> offers you predefined templates for "Bug report" and "Feature request", but allows you to tweak them before publishing, including selecting which labels to assign to each.



[GitHub Issues templates]: https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates
[manually add the Issue templates]: https://help.github.com/en/github/building-a-strong-community/manually-creating-a-single-issue-template-for-your-repository

**Comment by fantaisie-software** [comment]
I think it will be too much hassle to get them all here. I will create a subforums on the PB forums dedicated to IDE bugs and move all the related bugs in here. If someone wants to pick one, it will be easier and it could create the PR directly.

**Comment by fantaisie-software** [comment]
It's done.

**Comment by tajmone** [comment]
@fantaisie-software:

> I think it will be too much hassle to get them all here. I will create a subforums on the PB forums dedicated to IDE bugs and move all the related bugs in here. If someone wants to pick one, it will be easier and it could create the PR directly.

Probably the best approach, since the vast majority of PB users are going to stick to the forum. Issues could then be used mainly by actual contributors, so the focus is kept on code fixes.

Of course, if someone does open an IDE-bug Issue here we'll treat just like any other Issue (and use labels to keep track of topics across operations and discussions).

In any case, if in the future we ever need to move some bug reports here (or to a dedicate repository for the task), the above information could still be useful to optimize the experience.

We could close this Issue, and just reopen it if the need ever arises again.
