### ISSUE TITLE
Delete Unfinished Automation Sources

### ISSUE THREAD

**Issue by kpeters58** [fantaisie-software/purebasic#82]
From Automation.pb (in PurebasicIDE/sdk/):

>   If AUTO_Initialize("C:\PureBasic\v4.60\SDK\Automation\Automation.dll")

It's wrapped in CompilerIf #PB_Compiler_Debugger
I did not study this in detail, but it looks to me that this file should either be removed or fixed...

**Comment by tajmone** [comment]
Just pasting here a chunck of the code and a direct link to the source file. 

[`PureBasicIDE/sdk/Automation.pb`][Automation.pb] (LL 222-EOF):

```purebasic
CompilerIf #PB_Compiler_Debugger
  
  Procedure AutoCompleteCallback(List Entries.s())
    Debug "have callback call"
    ForEach Entries()
      Debug Entries()
      Entries() + "XX"
    Next
  EndProcedure
  
  
  If AUTO_Initialize("C:\PureBasic\v4.60\SDK\Automation\Automation.dll")
    If AUTO_ConnectToAny()
      AUTO_RegisterEvent("AutoComplete", @AutoCompleteCallback())
      
      Debug AUTO_MenuCommand("Preferences")
      
      AUTO_ProcessEvents(100000)
      AUTO_Disconnect()
    Else
      Debug AUTO_LastError()
    EndIf
    
    AUTO_Shutdown()
  EndIf
  
CompilerEndIf
```




[Automation.pb]: https://github.com/fantaisie-software/purebasic/blob/master/PureBasicIDE/sdk/Automation.pb#L233

**Comment by t-harter** [comment]
It is just an example/test code for the unfinished automation feature. It is not used currently. I don't think it makes sense to work on this unless somebody wants to get serious and really finish that feature.

As I said elsewhere, it may make more sense to remove this feature entirely since I don't think there is a large userbase for this feature. Even less so now since people can just built their own modified IDE if they want to.

Other files related to this:
[PureBasicIDE/Automation.pb](https://github.com/fantaisie-software/purebasic/blob/master/PureBasicIDE/Automation.pb)
[PureBasicIDE/AutomationDomainSocket.c](https://github.com/fantaisie-software/purebasic/blob/master/PureBasicIDE/AutomationDomainSocket.c)
[PureBasicIDE/AutomationLibrary.pb](https://github.com/fantaisie-software/purebasic/blob/master/PureBasicIDE/AutomationLibrary.pb)
[PureBasicIDE/RemoteProcedureCall.pb](https://github.com/fantaisie-software/purebasic/blob/master/PureBasicIDE/RemoteProcedureCall.pb)

**Comment by fantaisie-software** [comment]
I agree with Timo, let just remove these files as it doesn't makes much sense now
