### ISSUE TITLE
Linux Crash

### ISSUE THREAD

**Issue by mk-soft-65** [fantaisie-software/purebasic#92]
The crash under Linux with opened Procedure Browser is eliminated. The g_object is not valid and leads to stack errors.

At the moment try to create a pull request. So far without success. Have no experience with GitHub yet.

How to upload files?

Sorry, my English is very bad

**Comment by SicroAtGit** [comment]
First, we should clarify whether this should be a hotfix or whether the bug should be released with the next release. Without clarifying this, it's not clear which branch should be used as the basis for this commit (master or v5.72). @fantaisie-software what do you think?

**Comment by tajmone** [comment]
Hi @mk-soft-65! Thanks for joining the project and helping, it's really appeciated.


> At the moment try to create a pull request. So far without success. Have no experience with GitHub yet.

I've seen your pull-request #93, and yes, there's something wrong there. First of all, you're trying to merge from your `master` branch into branch `v5.72`, whereas your local changes should be in a custom branch (not `master` but named something else, like `linuxcrash` for example) so that you don't compromise your `master` branch. Second, all pull requests should be made to the `master` branch of this repository (in the near future this will change though).

> How to upload files?

Ideally you should use Git, via command line or using a GUI frontend of your choice. You can also upload files directly from the browser using GitHub's WebUI, but it's not as flexible and practical as using Git or a Git GUI client.

Not knowing on which OS you work on, which tools you use and what's your level of experience with Git, it's hard to provide a direct answer.

We've provided some basic guidelines in the [`CONTRIBUTING.md`][CONTRIBUTING.md] document, so you might want to check these two section of the document:

- [Contributing to the Repository]
- [Working on GitHub]

You should find there some useful information on how to contribute to this project, as well as to where to start with Git and GitHub, by following the selected brief tutorials (including some interactive tutorials).

You'll also find links to free Git clients for the various OSs, so if you're new to Git you might want to use a GUI which simplifies the whole process by offering a visual overview of the project, its history and the various operations you to carry out.

Hopefully that material can help you get started, but of course we can help you with specific tasks if you're facing trouble doing some specific steps (we have all been there, so it's normal).

> Sorry, my English is very bad

Don't worry, it won't prevent you from contributing.

[Contributing to the Repository]: https://github.com/fantaisie-software/purebasic/blob/master/CONTRIBUTING.md#contributing-to-the-repository
[CONTRIBUTING.md]: https://github.com/fantaisie-software/purebasic/blob/master/CONTRIBUTING.md
[Working on GitHub]: https://github.com/fantaisie-software/purebasic/blob/master/CONTRIBUTING.md#working-on-github

**Comment by tajmone** [comment]
> Sorry, my English is very bad

_Git Magic_ is a good book to start learning Git, and it's available in many languages, maybe also in your native language:

http://www-cs-students.stanford.edu/~blynn//gitmagic/

**Comment by SicroAtGit** [comment]
I can recommend you this free German book to start with Git:

http://gitbu.ch/
